# Generated by Django 5.1.3 on 2024-11-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
